services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: npm run dev
